// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type MarmotCidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Prefix    [4]uint8
}

// LoadMarmot returns the embedded CollectionSpec for Marmot.
func LoadMarmot() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MarmotBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Marmot: %w", err)
	}

	return spec, err
}

// LoadMarmotObjects loads Marmot and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MarmotObjects
//	*MarmotPrograms
//	*MarmotMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMarmotObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMarmot()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MarmotSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MarmotSpecs struct {
	MarmotProgramSpecs
	MarmotMapSpecs
	MarmotVariableSpecs
}

// MarmotProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MarmotProgramSpecs struct {
	TcIngress *ebpf.ProgramSpec `ebpf:"tc_ingress"`
}

// MarmotMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MarmotMapSpecs struct {
	CidrWhitelist *ebpf.MapSpec `ebpf:"cidr_whitelist"`
	StatsMap      *ebpf.MapSpec `ebpf:"stats_map"`
}

// MarmotVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MarmotVariableSpecs struct {
}

// MarmotObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMarmotObjects or ebpf.CollectionSpec.LoadAndAssign.
type MarmotObjects struct {
	MarmotPrograms
	MarmotMaps
	MarmotVariables
}

func (o *MarmotObjects) Close() error {
	return _MarmotClose(
		&o.MarmotPrograms,
		&o.MarmotMaps,
	)
}

// MarmotMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMarmotObjects or ebpf.CollectionSpec.LoadAndAssign.
type MarmotMaps struct {
	CidrWhitelist *ebpf.Map `ebpf:"cidr_whitelist"`
	StatsMap      *ebpf.Map `ebpf:"stats_map"`
}

func (m *MarmotMaps) Close() error {
	return _MarmotClose(
		m.CidrWhitelist,
		m.StatsMap,
	)
}

// MarmotVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadMarmotObjects or ebpf.CollectionSpec.LoadAndAssign.
type MarmotVariables struct {
}

// MarmotPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMarmotObjects or ebpf.CollectionSpec.LoadAndAssign.
type MarmotPrograms struct {
	TcIngress *ebpf.Program `ebpf:"tc_ingress"`
}

func (p *MarmotPrograms) Close() error {
	return _MarmotClose(
		p.TcIngress,
	)
}

func _MarmotClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed marmot_bpfel.o
var _MarmotBytes []byte
